#!/bin/bash
# Manual Agent Update Script
# Use this to update each agent individually

CORE_IP="10.243.99.44"
CORE_URL="http://${CORE_IP}:8000"

echo "=== Manual Agent Update Instructions ==="
echo ""
echo "Core Server URL: ${CORE_URL}"
echo ""
echo "For each agent, run these commands:"
echo ""
echo "# Agent 1: moria-pi (10.243.14.179)"
echo "ssh methinked@10.243.14.179"
echo "cd ~/nexus-agent"
echo "sed -i 's|NEXUS_CORE_URL=.*|NEXUS_CORE_URL=http://10.243.99.44:8000|g' .env"
echo "rm -f data/agent_state.json"
echo "pkill -f 'python.*nexus.agent.main' || true"
echo "sleep 2"
echo "nohup venv/bin/python -m nexus.agent.main > agent.log 2>&1 &"
echo "exit"
echo ""
echo "# Agent 2: raspberrypi (10.243.151.228)"
echo "ssh methinked@10.243.151.228"
echo "cd ~/nexus-agent"
echo "sed -i 's|NEXUS_CORE_URL=.*|NEXUS_CORE_URL=http://10.243.99.44:8000|g' .env"
echo "rm -f data/agent_state.json"
echo "pkill -f 'python.*nexus.agent.main' || true"
echo "sleep 2"
echo "nohup venv/bin/python -m nexus.agent.main > agent.log 2>&1 &"
echo "exit"
echo ""
echo "After updating both agents, verify in the dashboard:"
echo "  http://10.243.99.44:8000"
