"""
Configuration management commands.

Handles CLI configuration initialization and management.
"""

import sys
from pathlib import Path

import typer
from rich.console import Console
from rich.prompt import Confirm, Prompt
from rich.table import Table

from nexus.shared.config import CLIConfig

app = typer.Typer(help="Configuration management")
console = Console()


@app.command()
def init(
    core_url: str = typer.Option(
        None,
        "--core-url",
        "-u",
        help="URL of the Core server",
    ),
    force: bool = typer.Option(
        False,
        "--force",
        "-f",
        help="Overwrite existing configuration",
    ),
) -> None:
    """
    Initialize CLI configuration.

    Creates a .env file with configuration settings.
    """
    env_file = Path(".env")

    # Check if .env already exists
    if env_file.exists() and not force:
        console.print("[yellow]Configuration file .env already exists.[/yellow]")
        if not Confirm.ask("Overwrite existing configuration?"):
            console.print("[red]Aborted.[/red]")
            raise typer.Exit(1)

    # Interactive prompts
    console.print("\n[bold cyan]Nexus CLI Configuration[/bold cyan]\n")

    if not core_url:
        core_url = Prompt.ask(
            "Core server URL",
            default="http://localhost:8000",
        )

    # Optional: API token (can be set later)
    api_token = Prompt.ask(
        "API token (optional, press Enter to skip)",
        default="",
    )

    output_format = Prompt.ask(
        "Output format",
        choices=["rich", "json", "plain"],
        default="rich",
    )

    log_level = Prompt.ask(
        "Log level",
        choices=["debug", "info", "warning", "error"],
        default="info",
    )

    # Write configuration
    config_content = f"""# Nexus CLI Configuration
# Generated by: nexus config init

# Core Server
NEXUS_CORE_URL={core_url}

# Authentication
NEXUS_API_TOKEN={api_token}

# Output
NEXUS_OUTPUT_FORMAT={output_format}
NEXUS_LOG_LEVEL={log_level}
"""

    env_file.write_text(config_content)
    console.print(f"\n[green]✓[/green] Configuration saved to {env_file}")
    console.print("\nYou can now use the [bold]nexus[/bold] command to manage your fleet.")


@app.command()
def show() -> None:
    """
    Show current configuration.

    Displays all configuration settings from environment and .env file.
    """
    config = CLIConfig()

    table = Table(title="Nexus CLI Configuration", show_header=True)
    table.add_column("Setting", style="cyan", no_wrap=True)
    table.add_column("Value", style="white")

    # Core settings
    table.add_row("Core URL", config.core_url)
    table.add_row(
        "API Token",
        "***" + config.api_token[-8:] if config.api_token else "[red]Not set[/red]",
    )

    # Output settings
    table.add_row("Output Format", config.output_format)
    table.add_row("Log Level", config.log_level)

    # Security settings (masked)
    table.add_row("Shared Secret", "***" + config.shared_secret[-8:])
    table.add_row("JWT Algorithm", config.jwt_algorithm)
    table.add_row("JWT Expiration", f"{config.jwt_expiration_hours} hours")

    console.print()
    console.print(table)
    console.print()


@app.command()
def set(
    key: str = typer.Argument(..., help="Configuration key to set"),
    value: str = typer.Argument(..., help="Configuration value"),
) -> None:
    """
    Set a configuration value.

    Updates the .env file with the new value.
    """
    env_file = Path(".env")

    # Map of allowed keys to env var names
    allowed_keys = {
        "core-url": "NEXUS_CORE_URL",
        "token": "NEXUS_API_TOKEN",
        "output-format": "NEXUS_OUTPUT_FORMAT",
        "log-level": "NEXUS_LOG_LEVEL",
    }

    if key not in allowed_keys:
        console.print(f"[red]Error: Unknown configuration key '{key}'[/red]")
        console.print(f"\nAllowed keys: {', '.join(allowed_keys.keys())}")
        raise typer.Exit(1)

    env_var = allowed_keys[key]

    # Read existing .env or create new
    if env_file.exists():
        lines = env_file.read_text().splitlines()
    else:
        lines = ["# Nexus CLI Configuration"]

    # Update or append the key
    found = False
    for i, line in enumerate(lines):
        if line.startswith(f"{env_var}="):
            lines[i] = f"{env_var}={value}"
            found = True
            break

    if not found:
        lines.append(f"{env_var}={value}")

    # Write back
    env_file.write_text("\n".join(lines) + "\n")
    console.print(f"[green]✓[/green] Configuration updated: {key} = {value}")


@app.command()
def validate() -> None:
    """
    Validate configuration and test connectivity to Core server.
    """
    import httpx

    config = CLIConfig()

    console.print("\n[bold cyan]Validating Configuration[/bold cyan]\n")

    # Check core URL
    console.print(f"Core URL: {config.core_url}")

    # Try to connect to Core
    try:
        with console.status("[bold green]Connecting to Core server..."):
            response = httpx.get(f"{config.core_url}/health", timeout=5.0)
            response.raise_for_status()
            health = response.json()

        console.print(f"[green]✓[/green] Core server is reachable")
        console.print(f"  Status: {health.get('status', 'unknown')}")
        console.print(f"  Version: {health.get('version', 'unknown')}")

    except httpx.ConnectError:
        console.print(f"[red]✗[/red] Could not connect to Core server")
        console.print(f"  Make sure the Core server is running at {config.core_url}")
        raise typer.Exit(1)
    except httpx.HTTPStatusError as e:
        console.print(f"[red]✗[/red] Core server returned error: {e.response.status_code}")
        raise typer.Exit(1)
    except Exception as e:
        console.print(f"[red]✗[/red] Unexpected error: {e}")
        raise typer.Exit(1)

    # Check API token if present
    if config.api_token:
        console.print(f"[green]✓[/green] API token is configured")
    else:
        console.print(f"[yellow]⚠[/yellow] API token is not set (some commands may fail)")

    console.print("\n[green]Configuration is valid![/green]\n")
