"""
Nexus shared module.

Provides common models, configuration, and utilities used across Core, Agent, and CLI.
"""

from nexus.shared.auth import (
    AuthError,
    TokenExpiredError,
    TokenInvalidError,
    create_access_token,
    hash_password,
    verify_password,
    verify_shared_secret,
    verify_token,
)
from nexus.shared.config import AgentConfig, BaseConfig, CLIConfig, CoreConfig
from nexus.shared.models import (
    BaseResponse,
    ContainerStatus,
    Deployment,
    DeploymentConfig,
    DeploymentCreate,
    DeploymentList,
    DeploymentStatus,
    DeploymentUpdate,
    DeploymentWithDetails,
    DiskInfo,
    DiskType,
    ErrorResponse,
    HealthResponse,
    HealthThresholds,
    Job,
    JobCreate,
    JobList,
    JobResult,
    JobStatus,
    JobType,
    LogCreate,
    LogEntry,
    LogLevel,
    LogList,
    Metric,
    MetricCreate,
    MetricData,
    MetricList,
    MetricStats,
    Node,
    NodeCreate,
    NodeHealth,
    NodeHealthStatus,
    NodeList,
    NodeMetadata,
    NodeStatus,
    NodeUpdate,
    NodeWithMetrics,
    RegistrationRequest,
    RegistrationResponse,
    Service,
    ServiceCreate,
    ServiceList,
    ServiceUpdate,
    SystemInfo,
    Token,
    TokenData,
)

__all__ = [
    # Auth
    "AuthError",
    "TokenExpiredError",
    "TokenInvalidError",
    "create_access_token",
    "verify_token",
    "verify_shared_secret",
    "hash_password",
    "verify_password",
    # Config
    "BaseConfig",
    "CoreConfig",
    "AgentConfig",
    "CLIConfig",
    # Models - Node
    "Node",
    "NodeCreate",
    "NodeUpdate",
    "NodeList",
    "NodeMetadata",
    "NodeStatus",
    "NodeWithMetrics",
    # Models - Job
    "Job",
    "JobCreate",
    "JobList",
    "JobResult",
    "JobType",
    "JobStatus",
    # Models - Metric
    "Metric",
    "MetricCreate",
    "MetricData",
    "MetricList",
    "MetricStats",
    "NodeHealth",
    "NodeHealthStatus",
    "HealthThresholds",
    # Models - Log
    "LogEntry",
    "LogCreate",
    "LogList",
    "LogLevel",
    # Models - Service (Phase 7 - Docker Orchestration)
    "Service",
    "ServiceCreate",
    "ServiceUpdate",
    "ServiceList",
    # Models - Deployment (Phase 7 - Docker Orchestration)
    "Deployment",
    "DeploymentCreate",
    "DeploymentUpdate",
    "DeploymentList",
    "DeploymentStatus",
    "DeploymentConfig",
    "DeploymentWithDetails",
    "ContainerStatus",
    # Models - Disk Storage (Phase 6.5 - Multi-Disk Support)
    "DiskInfo",
    "DiskType",
    # Models - Auth
    "Token",
    "TokenData",
    "RegistrationRequest",
    "RegistrationResponse",
    # Models - System
    "SystemInfo",
    "HealthResponse",
    "ErrorResponse",
    "BaseResponse",
]
