"""
Nexus shared module.

Provides common models, configuration, and utilities used across Core, Agent, and CLI.
"""

from nexus.shared.auth import (
    AuthError,
    TokenExpiredError,
    TokenInvalidError,
    create_access_token,
    hash_password,
    verify_password,
    verify_shared_secret,
    verify_token,
)
from nexus.shared.config import AgentConfig, BaseConfig, CLIConfig, CoreConfig
from nexus.shared.models import (
    BaseResponse,
    DiskInfo,
    DiskType,
    ErrorResponse,
    HealthResponse,
    HealthThresholds,
    Job,
    InventoryUpdate,
    JobCreate,
    JobList,
    JobResult,
    JobStatus,
    JobType,
    LogCreate,
    LogEntry,
    LogLevel,
    LogList,
    Metric,
    MetricCreate,
    MetricData,
    MetricList,
    MetricStats,
    Node,
    NodeCreate,
    NodeHealth,
    NodeHealthStatus,
    NodeList,
    NodeMetadata,
    NodeStatus,
    NodeUpdate,
    NodeWithMetrics,
    RegistrationRequest,
    RegistrationResponse,
    SystemInfo,
    Token,
    TokenData,
    # Alerts
    Alert,
    AlertBase,
    AlertCreate,
    AlertList,
    AlertSeverity,
    AlertStatus,
    AlertType,
    AlertUpdate,
)

__all__ = [
    # Auth
    "AuthError",
    "TokenExpiredError",
    "TokenInvalidError",
    "create_access_token",
    "verify_token",
    "verify_shared_secret",
    "hash_password",
    "verify_password",
    # Config
    "BaseConfig",
    "CoreConfig",
    "AgentConfig",
    "CLIConfig",
    # Models - Node
    "Node",
    "NodeCreate",
    "NodeUpdate",
    "NodeList",
    "NodeMetadata",
    "NodeStatus",
    "NodeWithMetrics",
    "InventoryUpdate",
    # Models - Job
    "Job",
    "JobCreate",
    "JobList",
    "JobResult",
    "JobType",
    "JobStatus",
    # Models - Metric
    "Metric",
    "MetricCreate",
    "MetricData",
    "MetricList",
    "MetricStats",
    "NodeHealth",
    "NodeHealthStatus",
    "HealthThresholds",
    # Models - Log
    "LogEntry",
    "LogCreate",
    "LogList",
    "LogLevel",
    # Models - Disk Storage (Phase 6.5 - Multi-Disk Support)
    "DiskInfo",
    "DiskType",
    # Models - Auth
    "Token",
    "TokenData",
    "RegistrationRequest",
    "RegistrationResponse",
    # Models - System
    "SystemInfo",
    "HealthResponse",
    "ErrorResponse",
    "BaseResponse",
    # Alerts
    "Alert",
    "AlertBase",
    "AlertCreate",
    "AlertList",
    "AlertSeverity",
    "AlertStatus",
    "AlertType",
    "AlertUpdate",
]
